%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%           Generated by MATLAB 9.6 and Fixed-Point Designer 6.3           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [y_t,u_t] = MPC_Simulator_wrapper_fixpt(ref_1,ref_2,noise,T,H,q_,E,F1,z_min,z_max,n,m,N_h,A_d,B_d,C_d,Aob,Bob,Cob,Ld)
    fm = get_fimath();
    ref_1_in = fi( ref_1, 0, 16, 14, fm );
    ref_2_in = fi( ref_2, 0, 16, 14, fm );
    noise_in = fi( noise, 1, 16, 19, fm );
    T_in = fi( T, 0, 10, 0, fm );
    H_in = fi( H, 1, 16, 11, fm );
    q__in = fi( q_, 1, 16, 14, fm );
    E_in = fi( E, 1, 16, 14, fm );
    F1_in = fi( F1, 0, 16, 16, fm );
    z_min_in = fi( z_min, 1, 5, 0, fm );
    z_max_in = fi( z_max, 0, 4, 0, fm );
    n_in = fi( n, 0, 3, 0, fm );
    m_in = fi( m, 0, 2, 0, fm );
    N_h_in = fi( N_h, 0, 3, 0, fm );
    A_d_in = fi( A_d, 0, 16, 16, fm );
    B_d_in = fi( B_d, 0, 16, 16, fm );
    C_d_in = fi( C_d, 0, 16, 13, fm );
    Aob_in = fi( Aob, 0, 16, 15, fm );
    Bob_in = fi( Bob, 0, 16, 16, fm );
    Cob_in = fi( Cob, 0, 16, 13, fm );
    Ld_in = fi( Ld, 1, 16, 14, fm );
    [y_t_out,u_t_out] = MPC_Simulator_fixpt( ref_1_in, ref_2_in, noise_in, T_in, H_in, q__in, E_in, F1_in, z_min_in, z_max_in, n_in, m_in, N_h_in, A_d_in, B_d_in, C_d_in, Aob_in, Bob_in, Cob_in, Ld_in );
    y_t = double( y_t_out );
    u_t = double( u_t_out );
end

function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
